# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c72213e08f8f38cc3c68c394c0217d51025981ac90819a3503e9d079227ddd927fe551270efb3062521b849cc5178f31633dcb0890951666a72951c1d0b2663

test:
  secret_key_base: 89989c4406e5ded93caa56b898214a813232ed0662b68dbcd3f988c84c889fc93a2c3a5603912199ce7fcb088905f804ac225a85bdeda5c0d2903cbac94106c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
